services:
  db:
    image: postgres:16
    container_name: covestack-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: covestack
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: covestack-redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:3
    container_name: covestack-localstack
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=${S3_REGION:-us-east-1}
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  db_data:
  localstack_data:
